### ISSUE TITLE
Is there a possibility to customize the length of the time window when using the PICKRF module?

### ISSUE THREAD

**Issue by LevCarlo** [xumi1993/seispy#12]
A wonderful tool, especially for a newbie of receiver functions.

When I used the `pickrf` to my own data, due to the time window is too long, it's not convenient to focus the desiring seismic phases. Thus I would suggest adding the customizing setting for time window length.

**Comment by xumi1993** [comment]
The latest version has involved the feature into the `pickrf`. Append `-x xmax` to `pickrf` as following to set up the time length

```
pickrf -x 10 /path/to/rfs
```
the time length will be set to `[-2, 10]`.

**Comment by LevCarlo** [comment]
> The latest version has involved the feature into the `pickrf`. Append `-x xmax` to `pickrf` as following to set up the time length
> 
> ```
> pickrf -x 10 /path/to/rfs
> ```
> 
> the time length will be set to `[-2, 10]`.

Thanks！
