### ISSUE TITLE
how to write numpy.ndarray to a sacfile without missing  required header info

### ISSUE THREAD

**Issue by datseismo** [xumi1993/seispy#15]
Hii, seispy developer, I am running your example script https://seispy.xumijian.me/usage/calrf.html for gaining some knowledge regarding receiver functions.I have a very small querry, can the numpy.ndarray can be saved to the sac file after this step 
PRF_R, RMS, it = seispy.decon.deconit(R, Z, dt, R.shape[0], shift, f0, tmax, minderr)
I want to write PRF_R to be saved in sac file by something PRF_R.write('outfile',format='SAC'), When i does it gives error AttributeError: 'numpy.ndarray' object has no attribute 'write'

I hope developers may help me overcoming my problem.Thanks in advance.

**Comment by xumi1993** [comment]
Good idea, I'm considering add this function in next stable version.

**Comment by xumi1993** [comment]
In current version, this feature has been added to `seispy.decon.RFTrace`, inheriting from `obspy.core.Trace`. Please see [usage](https://seispy.xumijian.me/usage/calrf.html#calculate-prf) in detail.
