### ISSUE TITLE
Encounter "No earthquakes matched, please check configurations." with different location code

### ISSUE THREAD

**Issue by liucongcong20** [xumi1993/seispy#16]
Hello, seispy developer, when I ran the script,I found that the 28th line of the 'eq.py' script indicated that  the seismic event must have three components. However, when matching seismic events, the number of components of seismic events due to different location codes will be multiples of three.
For example, if there are six or nine components, it will prompt "No earthquakes matched, please check configurations." , but it is difficult for user to know what caused it. 
I think it is possible to add a judgment statement after line 28 in the 'eq.py' script whether each earthquakes event has only three components. If not, you can prompt "Each earthquake event in the file has more than three components, please select to delete redundant seismic components" .

**Comment by xumi1993** [comment]
This issue has been corrected in this version
