### ISSUE TITLE
how to prepare offline station data for rf study

### ISSUE THREAD

**Issue by datseismo** [xumi1993/seispy#26]
Hii seispy developer. How to prepare complete raw data collected from a offline station for receiver function processing.
1) event search
2) cutting waveform based on epicentral distance range etc...
3) association of events

**Comment by xumi1993** [comment]
The raw data should be cut including P arrival, such as 

- From 100 to 1000s relative to origin time. The 100 needs to be set to `offset` in configure file.
- From -100 to 200s around theoretical P arrival. In this case, the `omarker` and `kztime` should be the origin time, `b` should be the relative time length referring to `omarker`, and the `offset` is set to empty in configure file

Note that the `stla`, `stlo` and `stel` in sac header are also required for `prf` scheme.

**Comment by datseismo** [comment]
How can it be done,  can you please provide supportive codes. I don't find any relevents codes in your package.

**Comment by xumi1993** [comment]
Sorry, it isn't a part of Seispy.

**Comment by datseismo** [comment]
As a new user to receiver functions, It would be better if you can provide/suggest ready made code  doing this. I have only raw data recorded in a station saved in a directory. How can i compute rf using the same data sets. I have only stla,stlo,elevation information.

**Comment by xumi1993** [comment]
Cutting out event records from raw data is a basic skill for seismic data processing. The raw data also have different formats in Reftek, mseed, segy and SAC. The arrangement of these data is also different when they were extracted from data loggers. So it's difficult to develop a unified method to prepare the data.

**Comment by datseismo** [comment]
So seispy cannot be implemented for any offline stations, right?

**Comment by xumi1993** [comment]
You can cut out event data first and then use Seispy for RF calculation.

**Comment by datseismo** [comment]
ok sir, as i am new to this field i donot know how to cut the data wrt P onset time. I already converted 1 hr data files to the sac format.Does it require to merge whole data sets
