### ISSUE TITLE
'RFTrace' not defined

### ISSUE THREAD

**Issue by benkalyx** [xumi1993/seispy#27]
hello developer,
I quite enjoy your code on rf analysis. following the example and the script, i got stuck during deconvolution processing.
here is my code
f0 = 2.0
itmax = 400
minderr = 0.001
rf = RFTrace.deconvolute(st_rot[1], st_rot[2], 
                         method='iter', 
                         tshift=shift, 
                         f0=f0, 
                         itmax=itmax, 
                         minderr=minderr)
rf.plot(show = False, type = 'relative',
       starttime = rf.stats.starttime + shift,
       endtime = rf.stats.starttime + shift + 30)

And here is the response
NameError                                 Traceback (most recent call last)
Input In [12], in <module>
      2 itmax = 400
      3 minderr = 0.001
----> 4 rf = RFTrace.deconvolute(st_rot[1], st_rot[2], 
      5                          method='iter', 
      6                          tshift=shift, 
      7                          f0=f0, 
      8                          itmax=itmax, 
      9                          minderr=minderr)
     10 rf.plot(show = False, type = 'relative',
     11        starttime = rf.stats.starttime + shift,
     12        endtime = rf.stats.starttime + shift + 30)

NameError: name 'RFTrace' is not defined

Please help. I'm a new user
Thank you

**Comment by xumi1993** [comment]
Pls import `RFTrace` first with

```python
 from seispy.decon import RFTrace
```

**Comment by benkalyx** [comment]
thank you for your reply. working now

**Comment by datseismo** [comment]
@benkalyx do you have any idea on my queries. please help me.
