### ISSUE TITLE
When selecting QRF, there is no file matching the file pattern

### ISSUE THREAD

**Issue by liucongcong20** [xumi1993/seispy#32]
**Describe the bug**
When BEZ rotate to QRT and QRF is selected, the terminal will prompt an exception 'No file matching file pattern: ./*/*_ L.sac’. Then I found that in the  rpickfigure.py script, the '*P_Q.sac' on lines 49 and 50 corresponds to the 'self.comp = 'L'' on line 51.
**Expected behavior**
Replace "L" with "Q" in line 51.
**Error raised**
![Screenshot from 2022-03-30 10-37-27](https://user-images.githubusercontent.com/92346155/160740734-fd0d17bf-c349-4df6-9e13-372ef8d38fa2.png)
![Screenshot from 2022-03-30 10-38-10](https://user-images.githubusercontent.com/92346155/160740798-3cb3c65b-1067-4e18-a08e-26a7fbbff6c5.png)
![Screenshot from 2022-03-30 10-39-17](https://user-images.githubusercontent.com/92346155/160740835-0d94050b-3a5b-4af6-9a1c-26c8d93ad8c9.png)

**Platform (please complete the following information):**
 - OS: [e.g. MacOS]   Linux 
 - Version [e.g. 1.2.14]  Ubuntu 20.04

**Additional context**

**Comment by xumi1993** [comment]
Hi,

Thank you very much. I've corrected it on the _dev_ branch, which will be merged into the _main_ branch in the next month. 
You can use install the _dev_ branch manually to test it.
```
git clone --branch=dev https://github.com/xumi1993/seispy.git
cd seispy
pip install .
```

BR//Mijian

**Comment by liucongcong20** [comment]
> Hi,
> 
> Thank you very much. I've corrected it on the _dev_ branch, which will be merged into the _main_ branch in the next month. You can use install the _dev_ branch manually to test it.
> 
> ```
> git clone --branch=dev https://github.com/xumi1993/seispy.git
> cd seispy
> pip install .
> ```
> 
> BR//Mijian
