### ISSUE TITLE
Some bugs when running rf2depth.

### ISSUE THREAD

**Issue by Deg2v** [xumi1993/seispy#35]
**Describe the bug**

When running rf2depth ccp.cfg, some bugs happend:

```Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/seispy/bin/rf2depth", line 10, in <module>
    sys.exit(rf2depth())
  File "/home/dell/anaconda3/envs/seispy/lib/python3.8/site-packages/seispy/rf2depth_makedata.py", line 183, in rf2depth
    makedata(cpara)
  File "/home/dell/anaconda3/envs/seispy/lib/python3.8/site-packages/seispy/rf2depth_makedata.py", line 98, in makedata
    PS_RFdepth, end_index, x_s, _ = psrf2depth(stadatar, cpara.depth_axis,
  File "/home/anaconda3/envs/seispy/lib/python3.8/site-packages/seispy/rfcorrect.py", line 298, in psrf2depth
    tps[i], x_s[i], x_p[i] = xps_tps_map(dep_mod, rayp, stadatar.rayp[i])
  File "/home/dell/anaconda3/envs/seispy/lib/python3.8/site-packages/seispy/rfcorrect.py", line 335, in xps_tps_map
    x_s = np.cumsum((dep_mod.dz / dep_mod.R) / np.sqrt((1. / (srayp ** 2. * (dep_mod.R / dep_mod.vs) ** -2)) - 1))
ValueError: operands could not be broadcast together with shapes (801,) (803,)
```
_I think there are some bugs about **topographic correction**. So I cancelled topographic correction for temporary use by adding `elevation=0` in **utils.py**._

Now it works, but there are still some warnings in Seispy 1.2.15, these warnings disappear when changing to version 1.2.14.

```
/home/dell/anaconda3/envs/seispy/lib/python3.8/site-packages/python_seispy-1.2.15-py3.8.egg/seispy/rfcorrect.py:387: RuntimeWarning: invalid value encountered in sqrt
  x_p = np.cumsum((dep_mod.dz / dep_mod.R) / np.sqrt((1. / (prayp ** 2. * (dep_mod.R / dep_mod.vp) ** -2)) - 1))
/home/dell/anaconda3/envs/seispy/lib/python3.8/site-packages/python_seispy-1.2.15-py3.8.egg/seispy/utils.py:78: RuntimeWarning: invalid value encountered in sqrt
  return np.cumsum((np.sqrt((dep_mod.R / dep_mod.vs) ** 2 - rayps ** 2) - np.sqrt((dep_mod.R / dep_mod.vp) ** 2 - raypp ** 2)) * (dep_mod.dz / dep_mod.R))
```

**Platform (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Additional context**

**Comment by xumi1993** [comment]
1. Is the elevation of the station less than 0?
2. In your warning, I think `(dep_mod.R / dep_mod.vp) ** 2 - raypp ** 2)` less than 0. Do you process the S-wave receiver function?

**Comment by Deg2v** [comment]
I process P-wave receiver function and the elevation is positive.

I undo `elevation=0` and add `print(rayp.shape,dep_mod.dz.shape)`before https://github.com/xumi1993/seispy/blob/03102d24e9d59a518403d7c2216fceebcbe43425/seispy/rfcorrect.py#L342
then test two station, station at 1340 print (801,) (803,); and another at 2900 print (801,) (804,)
so I think the `rayp`  does not match `dep_mod` https://github.com/xumi1993/seispy/blob/03102d24e9d59a518403d7c2216fceebcbe43425/seispy/rfcorrect.py#L340

**Comment by xumi1993** [comment]
I see. I think this error has been corrected in 1.2.15. 

```
/home/dell/anaconda3/envs/seispy/lib/python3.8/site-packages/python_seispy-1.2.15-py3.8.egg/seispy/rfcorrect.py:387: RuntimeWarning: invalid value encountered in sqrt
  x_p = np.cumsum((dep_mod.dz / dep_mod.R) / np.sqrt((1. / (prayp ** 2. * (dep_mod.R / dep_mod.vp) ** -2)) - 1))
/home/dell/anaconda3/envs/seispy/lib/python3.8/site-packages/python_seispy-1.2.15-py3.8.egg/seispy/utils.py:78: RuntimeWarning: invalid value encountered in sqrt
  return np.cumsum((np.sqrt((dep_mod.R / dep_mod.vs) ** 2 - rayps ** 2) - np.sqrt((dep_mod.R / dep_mod.vp) ** 2 - raypp ** 2)) * (dep_mod.dz / dep_mod.R))
```
This error is raised when calculating  `Tps` at large depth because of `dep_mod.R / dep_mod.vp` larger than `raypp`. Thus the `Tps` will be assigned to `np.nan` at this depth. This is why the PRFs are trimmed to less than 800 km, although you set up the `dep_max` to 800 km.

**Comment by Deg2v** [comment]
I am sorry I am confused about `"this error has been corrected in 1.2.15."`
In my test, these warning does not appear in 1.2.14.
I will try to set dep_max less than 800.

**Comment by xumi1993** [comment]
1. I mean the `ValueError: operands could not be broadcast together with shapes (801,) (803,)` has been corrected.
2. Different from this error, the warning was raised because I hid this warning in versions before 1.2.15.  So the warning is always there. Don't too worry about that. I'll catch this warning and write it into output logs.

**Comment by Deg2v** [comment]
Thank you, I understand the warning. 
As for the error, I create a new environment and install Seispy 1.2.15,  set `dep_end=750`, `dep_val=2`, the elevation is 240. It still reports the same error `ValueError: operands could not be broadcast together with shapes (376,) (377,)`.
So I was confused.

**Comment by xumi1993** [comment]
I see. I'll check the code these days

**Comment by xumi1993** [comment]
Do you extract Ps ray-parameters from an external library (i.e., specify `rayp_lib` in the configure file)?

**Comment by Deg2v** [comment]
Yes，you provide a `psrayp.npy` file. I've been using it since last year

**Comment by Deg2v** [comment]
After emptying the ray parameters, it runs normally.

**Comment by xumi1993** [comment]
Quickly, you can change the following line to
https://github.com/xumi1993/seispy/blob/03102d24e9d59a518403d7c2216fceebcbe43425/seispy/rfcorrect.py#L340
```
rayp = get_psrayp(rayp_lib, stadatar.dis[i], stadatar.evdp[i], dep_mod.depths_elev)
```
and try again. I just located this error without any change and test. Pls let me know if it works.

**Comment by Deg2v** [comment]
Yes, It works.

**Comment by xumi1993** [comment]
Great. It will be fixed in the next version. Thank you very much.

**Comment by Deg2v** [comment]
^O^.Thank you for your kind help and nice work.
