### ISSUE TITLE
Moveoutcorrect module

### ISSUE THREAD

**Issue by Hannah0363** [xumi1993/seispy#39]
Hi!!! I've tried the example of "moveout correction" shown in the [video at 01:30:30](http://seismo.training.ustc.edu.cn/index.php/video). But, there was an error of plotting.
 **Code**
rf_corr = rfsta.moveoutcorrect(dep_range=np.arange(0,200),ref_rayp=0.06)
correct_stack = np.mean(rf_corr,axis=0)
plt.plot(rfsta.time_axis,raw_stack)
plt.plot(rfsta.time_axis,correct_stack)
plt.xlim([-1,25])
**Error**
ValueError: x and y must have same first dimension, but have shapes (13001,) and (99, 13001)

Then, I checked the shape of "rf_corr"
AttributeError: 'tuple' object has no attribute 'shape'

However, the shape of "correct_stack" is  (99, 13001)!!! Why??
Shouldn't "correct_stack" be like (13001,) and "rf_corr" is (99, 13001)?

**Comment by xumi1993** [comment]
In the current version, the code can be written as 

```
rf_corr, t_corr = rfsta.moveoutcorrect(dep_range=np.arange(0,200),ref_rayp=0.06)
```

**Comment by Hannah0363** [comment]
It works! Thanks for your timely help!!!
