### ISSUE TITLE
prf  rf.cfg returns syntax error

### ISSUE THREAD

**Issue by benkalyx** [xumi1993/seispy#41]
Please I'm still learning how to run PRF for a single station with multiple events with the example you provided in the script but each time i run the command 'prf rf.cfg'. I keep getting  (invalid syntax)

Input In
    prf rf.cfg
        ^
SyntaxError: invalid syntax

thank you for your help

**Comment by xumi1993** [comment]
Hi, how do you install the package?

**Comment by benkalyx** [comment]
Hello, Thank you for your response.
I just noticed that the caret(^) was placed under prf instead of rf.cfg. The prf package was installed together with seispy using pip.
Here is the correct syntax error
Input In
    prf rf.cfg
        ^
SyntaxError: invalid syntax

**Comment by xumi1993** [comment]
I think you should run this command in shell, rather than in the python console

**Comment by benkalyx** [comment]
I'm running on Jupyter notebook. The arrow is to indicate the position of the caret.

**Comment by xumi1993** [comment]
`prf` is a shell command

**Comment by benkalyx** [comment]
Thank you for your response. It worked in shell but does that mean i have to run all the script in shell? i seemed confused because seispy is a python based module. A little explanation will help.
