### ISSUE TITLE
Encountered "[RF] ERROR: unconverted data remains: 5", what cause this?

### ISSUE THREAD

**Issue by LevCarlo** [xumi1993/seispy#43]
Hi seispy developer,
I tried to use `prf rf.cfg` to calculate RFs of a single station and encountered the following errors:
Here is command log:
`2022-07-13 15:28:36,837 [RF] INFO: Load station info from ./rawdata/1001
2022-07-13 15:28:36,838 [RF] INFO: Searching earthquakes from IRIS
2022-07-13 15:28:38,722 [RF] INFO: 22 earthquakes are found
2022-07-13 15:28:38,722 [RF] INFO: Match SAC files
2022-07-13 15:28:38,724 [RF] ERROR: unconverted data remains: 5`

**Comment by xumi1993** [comment]
I think you set the wrong format of `dateformat` in the `rf.cfg`. Pls refer to [Associate SAC files with events](https://seispy.xumijian.me/usage/rf-sta.html#associate-sac-files-with-events) in detail.

**Comment by LevCarlo** [comment]
> I think you set the wrong format of `dateformat` in the `rf.cfg`. Pls refer to [Associate SAC files with events](https://seispy.xumijian.me/usage/rf-sta.html#associate-sac-files-with-events) in detail.

OK, 3Q
