### ISSUE TITLE
Consult the seispy library for problems related to calculating a seismic event receiving function separately

### ISSUE THREAD

**Issue by EasonLIU1111** [xumi1993/seispy#44]
#Consult the seispy library for problems related to calculating a seismic event receiving function separately

---

1. Calculate PRF.Use example failed.The error content is as follows:
```python
File f:\Python\Python309\lib\site-packages\obspy\core\stream.py:643, in Stream.__getitem__(self, index)
    641     return self.__class__(traces=self.traces.__getitem__(index))
    642 else:
--> 643     return self.traces.__getitem__(index)

IndexError: list index out of range
```

`Windows 10`；
`Python 3.10.2`；
`pip install python-seispy`。

**Comment by xumi1993** [comment]
Pls provide more details for your test, such as 
- Which example do you test?
- The full output logs 
- The complete configure file.

**Comment by EasonLIU1111** [comment]
The problem has been solved. Sorry
