### ISSUE TITLE
No earthquakes matched! please help

### ISSUE THREAD

**Issue by benkalyx** [xumi1993/seispy#47]
Please I have been stuck with this response error. I checked the configuration  to see what could be wrong but I'm not so sure what else to check. The data set are raw data from station archives.
Here is the command and the response 

khalix@Khalix-VirtualBox:~/Desktop/RF$ prf rf.cfg
2022-09-23 17:56:02,221 [RF] INFO: Load station info from ./Data.N1.NGSA1
2022-09-23 17:56:02,269 [RF] INFO: Searching earthquakes from IRIS
2022-09-23 17:56:21,072 [RF] INFO: 176 earthquakes are found
2022-09-23 17:56:21,073 [RF] INFO: Match SAC files
2022-09-23 17:56:21,280 [RF] WARNING: No earthquakes matched, please check configurations.

Thank you

**Comment by xumi1993** [comment]
Could you provide the configuration file and some raw data (3 SAC files of an event are fine)?

**Comment by benkalyx** [comment]
Here is the data and the configuration file:

[Data_rfile.zip](https://github.com/xumi1993/seispy/files/9638875/Data_rfile.zip)

**Comment by xumi1993** [comment]
There are some issues in your SAC file
1. Seispy will associate earthquakes (from catalog) with sacfiles according to datetime information in filename or sac header. I think you cut out the waveform around P arrival. Thus you must specify the origin time `o` in sac header, and don't set up the `offset`.
2. Your sacfiles are cut with a short time span. You should re-cut out the sacfiles from raw data with a longer time span.
