### ISSUE TITLE
Azimuth Correction

### ISSUE THREAD

**Issue by snoltcaraway** [xumi1993/seispy#68]
I am using the RF package, and the data I am loading in from IRIS has EHZ,EH1,EH2 channels. The EH1 and EH2 channel azimuths need to be corrected by anywhere from -6 to +6 degrees, and EHZ dip needs to be changed from 90 to -90, depending on the station. It does not appear this package automatically corrects the azimuth. I see there is a baz_shift variable in rotate in RF and also seispy.eq.rotate_ZNE in the the seispy package. 

Is the baz_shift what I need or do I need to use seispy.eq.rotate_ZNE? If I need to use seispy.eq.rotate_ZNE, how do I implement this in the RF package and data I am loading in through query. 

Here is a snippet of the code I am using with rf.rotate(baz_shift=6)
rf.load_stainfo()
rf.search_eq(catalog='NEIC PDE')
print(rf.eq_lst) ##The matched event lists are listed.

rf.match_eq() 

rf.detrend()
rf.filter()
rf.cal_phase()
rf.rotate(baz_shift=6) #Like this?
rf.drop_eq_snr()
rf.save_raw_data()
rf.trim()
rf.deconv()

**Comment by snoltcaraway** [comment]
or perhaps its rf.baz_correct()

I am just not what internal variables I need to change.

**Comment by snoltcaraway** [comment]
It would be really helpful to have a rotateZNE() for the rf module like seispy.eq.rotateZNE(). 

Obspy also has a function like this.

**Comment by xumi1993** [comment]
Hi,
Please try `rf.baz_correct(correct_angle=-6)` after `rf.cal_phase()`
