### ISSUE TITLE
SRF CCP stacking

### ISSUE THREAD

**Issue by JouSF-1409** [xumi1993/seispy#75]
因为始终叠加不到bin里，在为SRF CCP stacking写点东西。

先说下bug原因。之前用相同台站做过PRF CCP stacking，结果比较准确。然后把里面xps的功能拆出来写了个时深转换的功能，PRF与SRF的Moho深度还比较一致。所以这个问题比较奇怪。

rayp写的是s/deg，SRF是倒转了时间序列的，没有给rayp_lib，也就是采用平面波假设。
速度模型这边，尝试了原始速度模型和Vp，Vs调换的速度模型

有几件内容想不太明白，可能是几个公式，几个功能比较重叠，给整迷糊了
1. 怎么计算SRF插值要用到的序列（之前写的时深转换只用到了一个速度（S for PRF, P for SRF）。如果考虑平面波假设的影响，现有的内容该怎么调整。）
2. 计算时深转换的时候，interp1d里面 raylength是什么用的，
3. 如果想写一个类似psrayp的 部件给SRF，在传给ccp部分的时候，要注意什么。

目前做完的一些简化的东西：

1. DepMod 添加一个classmethod ccp_mod， 识别速度模型类型(3d/fold/1d)并切片，导出DepthMod类。这样不用反复检查类型
3. 简化的RFStation类。RFSt，基于 collections的UserList，在操作上更接近于List，写了个生成头段的功能。

**Comment by xumi1993** [comment]
- 我没有实际做过SRF的工作，而且在可见的未来也不会从事这项工作。但CCP叠加原理上和PRF是一样的，所以SRF插值要用到的序列应该和PRF是一样的，只是Vp和Vs调换（假设射线参数一致）。具体其他细节可能需要咨询其他做过SRF的老师。
- `raylength`是射线在每一层走过的距离，大部分时候没有用到，保留这个参数是历史遗留问题，以防后面用到。
- 这两个功能是可以添加的，这些功能会对代码结构产生很大影响，由于目前用户较多，保证功能稳定是首要问题，这些基础功能改变之后，可能会影响所有调用它们的函数，必须进行所有基本功能的测试。
- 对于基本结构的修改，建议你每次修改一小部分代码时提交一次PR，否则在汇入`devel`分支时难度过大。
- 上一个PR，你的修改有一些bug，导致基本测试未通过，我已经修改，你可以现在的`devel`分支合并到你的分支，解决冲突，再 提交新的PR。

**Comment by JouSF-1409** [comment]
* 实际处理的时候对换过模型的Vp, Vs，仍然遇到了这个问题，我仔细梳理下原因
* 改进的变动量太大，新的改动主要是开新文件，然后慢慢迁移过去。
* 好，我仔细看看改动，先merge
