### ISSUE TITLE
prf -l 的本地目录遇到问题

### ISSUE THREAD

**Issue by niuniustore** [xumi1993/seispy#81]
当我使用download_catalog下载的地震目录去作为本地地震目录时，QUAKEML格式的目录可以顺利去做，但txt格式的就不可以顺利去做。
![微信图片_20240228090724](https://github.com/xumi1993/seispy/assets/156401102/5bdfbe73-48d5-4417-bbef-b6ff6f25e5f9)

![微信图片_20240228090808](https://github.com/xumi1993/seispy/assets/156401102/cca321f2-3181-4767-a692-505c9f4d58ff)

**Comment by xumi1993** [comment]
This issue has been corrected in v1.3.4, Please see d84929e for more detail
