### ISSUE TITLE
Download remote data issue

### ISSUE THREAD

**Issue by Wufaxing** [xumi1993/seispy#83]
**Describe the bug**
when i try to download XR.ST39, there are 2 erros:
2024-03-05 22:29:34,225 [RF] INFO: Load station info of XR.ST39 from IRIS web-service
2024-03-05 22:29:34,749 [RF] INFO: XR.ST39, latitude: 33.764, longitude: 88.400
2024-03-05 22:29:34,749 [RF] INFO: Searching earthquakes from IRIS
2024-03-05 22:29:41,680 [RF] INFO: 156 earthquakes are found
2024-03-05 22:29:41,681 [RF] INFO: Fetch seismic data from IRIS
2024-03-05 22:29:41,701 [RF] ERROR: More than one phase were calculated with source depth of 33.0 and distance of 14.551067692913245
2024-03-05 22:29:41,701 [RF] ERROR: cannot access local variable 'arr_time' where it is not associated with a value
                            date    evla    evlo  evdp  mag magtype
0    1998-07-12T07:16:16.640000Z  47.722  82.882  33.0  5.2     mwc
1    1998-07-15T04:36:01.080000Z  29.576  81.466  33.0  4.7      mb
2    1998-07-18T01:40:30.210000Z  35.303  81.560  33.0  4.6      mb
3    1998-07-18T06:21:17.010000Z  35.357  78.378  33.0  4.8      mb
4    1998-07-19T16:56:46.190000Z  35.517  78.286  33.0  4.8      mb
..                           ...     ...     ...   ...  ...     ...
151  1999-11-30T10:08:08.100000Z  36.306  81.273  33.0  4.9      mb
152  1999-12-01T13:56:43.750000Z  30.024  81.444  33.0  4.5      mb
153  1999-12-06T07:33:11.160000Z  42.629  76.322  20.9  5.2     mwc
154  1999-12-17T10:15:02.200000Z  40.759  77.272  33.0  4.5      mb
155  1999-12-20T11:46:54.290000Z  24.517  97.774  52.1  4.6      mb

[156 rows x 6 columns]
an error occurred: cannot access local variable 'arr_time' where it is not associated with a value

**Additional context**
while other stations like XR.ST00-XR.ST10 works well,here is my code:
rf = RF()
rf.para.data_server = 'IRIS'
rf.para.cata_server = 'IRIS'
rf.para.stainfo.network = 'XR'
rf.para.stainfo.station = 'ST39'
rf.para.stainfo.channel = 'BH?'
rf.para.stainfo.location = '01'
rf.para.datapath = './Data_INDEPTH3/{}.{}'.format(rf.para.stainfo.network, rf.para.stainfo.station) 
rf.para.use_remote_data = True

rf.para.ref_comp ='BHZ'
rf.para.phase = 'P'
rf.para.noisegate = 1
rf.para.magmin = 4.5
rf.para.dismin = 5
rf.para.dismax = 15
rf.para.depthmax = 80
rf.para.gauss = [0.5, 1.0, 1.5, 2.0] ##RF with different Gauss factor will be calculated simultaneously.
rf.para.rmsgate = 0.4
rf.para.freqmin = 0.05
rf.para.freqmax = 2.0
rf.para.comp = 'RTZ'

rf.para.date_begin = UTCDateTime('19970711')
rf.para.date_end = UTCDateTime('19991231')

rf.load_stainfo()
rf.search_eq(catalog='NEIC PDE')
print(rf.eq_lst) ##The matched event lists are listed
rf.match_eq()
rf.save_raw_data() 
rf.eqs.to_csv('{}/eqs.csv'.format(rf.para.datapath))

**Comment by xumi1993** [comment]
I think is not a bug. In this case, you have used distance range from 5 - 15 deg. The range is too small, so that more than 1 P phase will be generated.
