### ISSUE TITLE
1D raytracing +3D time difference correction in rf2depth

### ISSUE THREAD

**Issue by ShihChi90** [xumi1993/seispy#93]
**Describe the bug**
I was curious about how the 3D time correction was done, so I was browsing through the codes 
and noticed that if I provide an custom 1D model in the config file, the 3D perturbation model `mod3d` will be calculated base on the given custom 1D model, but the 1D raytracing still runs with default velmod (which is iasp91). I thought this might be an issue because the time difference for correction is not based on default model? 

![image](https://github.com/user-attachments/assets/a6ea208c-f717-4d7a-b82b-25703bdc7f5e)

**Expected behavior**
1D raytracing and 3D time difference correction using the same 1D velmod, when custom 1D model is given, they both use custom 1D model.

**Platform (please complete the following information):**
 - OS: Linux (red hat)
 - SeisPy Version 1.3.5

**Additional context**

**Comment by xumi1993** [comment]
Thanks for figuring it out. This bug has been fixed by commit [51164b8](https://github.com/xumi1993/seispy/commit/51164b8727ad51c81423a48e0a76d3ebe99a95e7). I will merge it to main branch soon.
Thank you very much.
